name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    name: OTP ${{matrix.pair.otp}} / Elixir ${{matrix.pair.elixir}}
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ecto_integration_repo
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              otp: 24.2
              elixir: 1.12
          - pair:
              otp: 26.2
              elixir: 1.16
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: "Compile and Test Library"
        run: |
          mix do deps.get, deps.compile, compile
          mix test --exclude distributed
          mix test --include distributed
      - name: "Compile and Test Examples"
        run: |
          cd examples/ecto_integration
          mix do deps.get, deps.compile, compile
          mix test
