name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    name: OTP ${{matrix.pair.otp}} / Elixir ${{matrix.pair.elixir}}
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ecto_integration_repo
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              otp: 25
              elixir: 1.14
          - pair:
              otp: 26
              elixir: 1.16
          - pair:
              otp: 27
              elixir: 1.17
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: "Start empd"
        run: |
          epmd -daemon
      - name: "Compile and Test Library"
        run: |
          mix do deps.get, deps.compile, compile
          mix test --exclude distributed --exclude finitomata
          mix test --exclude test --include distributed
      - name: "Test Library with itself in :finitomata env"
        run: |
          MIX_ENV=finitomata mix do deps.get, deps.compile, compile
          MIX_ENV=finitomata mix test --exclude test --include finitomata
      - name: "Compile and Test Ecto Examples"
        run: |
          cd examples/ecto_integration
          mix do deps.get, deps.compile, compile
          mix test
      - name: "Compile and Test Caches Examples"
        run: |
          cd examples/caches
          mix do deps.get, deps.compile, compile
          mix test
      - name: "Compile and Test ExUnit Testing Examples"
        run: |
          cd examples/ex_unit_testing
          mix do deps.get, deps.compile, compile
          mix test
      - name: "Compile and Test Telemetria Examples"
        run: |
          cd examples/telemetria
          mix do deps.get, deps.compile, compile
          mix test
